name: Monitor Inmobiliario Automático VES
on:
  schedule:
    # Se ejecuta cada 4 horas (en hora UTC)
    - cron: '0 */4 * * *'
  workflow_dispatch: # Permite ejecución manual desde la pestaña Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar Librerías
        run: |
          pip install pandas numpy undetected-chromedriver selenium webdriver-manager requests

      - name: Ejecutar Scraper
        env:
          # Estas variables se jalan de Settings > Secrets > Actions
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.CHAT_ID }}
          LATITUDE: ${{ secrets.LATITUDE }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
        run: python search_house.py
